# This file was generated by GoReleaser. DO NOT EDIT.
cask "test-trusted-go-releaser" do
  name "test-trusted-go-releaser"
  desc ""
  homepage "https://github.com/actionutils/test-trusted-go-releaser"
  version "0.0.53"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "test-trusted-go-releaser"

  on_macos do
    on_arm do
      url "https://github.com/actionutils/test-trusted-go-releaser/releases/download/v#{version}/test-trusted-go-releaser_#{version}_darwin_arm64.tar.gz"
      sha256 "906f6fc0fd2557debe84272ef32005ce858e61884d9554d0ffc1cb7056ce49d8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/actionutils/test-trusted-go-releaser/releases/download/v#{version}/test-trusted-go-releaser_#{version}_linux_arm64.tar.gz"
      sha256 "afb933d13537f86fde651c034f994f909549a83aed8da136b6142bf7d1ae2e45"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/test-trusted-go-releaser"]
    end
  end

  # No zap stanza required
end
