# This file was generated by GoReleaser. DO NOT EDIT.
cask "test-trusted-go-releaser" do
  name "test-trusted-go-releaser"
  desc ""
  homepage "https://github.com/actionutils/test-trusted-go-releaser"
  version "0.0.55"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "test-trusted-go-releaser"

  on_macos do
    on_arm do
      url "https://github.com/actionutils/test-trusted-go-releaser/releases/download/v#{version}/test-trusted-go-releaser_#{version}_darwin_arm64.tar.gz"
      sha256 "cb91234d136a96aadad0dba2c5d5f2ba80a22171bc6aef44e26c1cde12e82614"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/actionutils/test-trusted-go-releaser/releases/download/v#{version}/test-trusted-go-releaser_#{version}_linux_arm64.tar.gz"
      sha256 "248b37fe809312def0400639d71ea59598a4495cdfe3ede627826610d340548a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/test-trusted-go-releaser"]
    end
  end

  # No zap stanza required
end
