# This file was generated by GoReleaser. DO NOT EDIT.
cask "test-trusted-go-releaser" do
  name "test-trusted-go-releaser"
  desc ""
  homepage "https://github.com/actionutils/test-trusted-go-releaser"
  version "0.0.56"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "test-trusted-go-releaser"

  on_macos do
    on_arm do
      url "https://github.com/actionutils/test-trusted-go-releaser/releases/download/v#{version}/test-trusted-go-releaser_#{version}_darwin_arm64.tar.gz"
      sha256 "97a5b92bb280d02c937214ad8d6b6f0432be7f06da1c5672031b5d12c7217aff"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/actionutils/test-trusted-go-releaser/releases/download/v#{version}/test-trusted-go-releaser_#{version}_linux_arm64.tar.gz"
      sha256 "9ae4c60326bde6feee600ec2002861ce9e13598edc276c8d2566e4f6ede9642c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/test-trusted-go-releaser"]
    end
  end

  # No zap stanza required
end
